<?php
/** @var Ainstainer_TechTalk_Block_View $this
 * Created by PhpStorm.
 * User: timur
 * Date: 02.11.16
 * Time: 11:43
 */
ini_set('display_errors', 1);

?>
<ul>
    <li><?php echo $this->getRequestRecord()->getName()?> said:</li>
    <li><?php echo $this->getRequestRecord()->getComment()?></li>
</ul>

<h1>OTHER COMMENTS</h1>
<ul>
    <?php foreach($this->getOtherComments($this->getRequestRecord()->getRequest_id()) as $contact){?>
        <li><?php echo $contact->getName()?> said:</li>
        <li><?php echo $contact->getComment()?></li>
    <?php }?>
</ul>
